import unittest
from unittest.mock import patch, MagicMock
from pathlib import Path
import subprocess
import sys
import io
from contextlib import redirect_stdout

from main import run_pr

class TestMainPr(unittest.TestCase):

    def setUp(self):
        self.project_dir = Path("/tmp/test_project")
        self.project_dir.mkdir(exist_ok=True)
        (self.project_dir / ".git").mkdir(exist_ok=True)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.project_dir)

    @patch('shared.config_loader.load_config_from_file', return_value={'github_token': 'test_token'})
    @patch('shared.github_client.GitHubClient')
    @patch('subprocess.run')
    @patch('shared.git.get_remote_url', return_value='https://github.com/test-owner/test-repo.git')
    @patch('shared.git.get_current_branch', return_value='feature-branch')
    @patch('shutil.which', return_value='/usr/bin/git')
    def test_pr_create_success(self, mock_which, mock_get_current_branch, mock_get_remote_url, mock_subprocess_run, mock_github_client, mock_load_config):
        # Arrange
        args = MagicMock()
        args.action = 'create'
        args.project_dir = self.project_dir
        args.title = 'Test PR'
        args.body = 'This is a test PR.'
        args.base = 'main'
        args.draft = False
        args.profile = None

        mock_client_instance = mock_github_client.return_value
        mock_client_instance.get_repo_info_from_remote.return_value = ('github.com', 'test-owner', 'test-repo')
        mock_client_instance.create_pr.return_value = 'https://github.com/test-owner/test-repo/pull/1'

        # Act
        with self.assertRaises(SystemExit) as cm:
            run_pr(args)

        # Assert
        self.assertEqual(cm.exception.code, 0)
        mock_load_config.assert_called_once_with(profile=None)
        mock_github_client.assert_any_call(token='test_token')
        mock_github_client.assert_any_call(token='test_token', host='github.com')
        mock_client_instance.create_pr.assert_called_once_with(
            owner='test-owner',
            repo='test-repo',
            title='Test PR',
            body='This is a test PR.',
            head='feature-branch',
            base='main',
            draft=False
        )

    @patch('shared.config_loader.load_config_from_file', return_value={'github_token': 'test_token'})
    @patch('shared.github_client.GitHubClient')
    @patch('subprocess.run')
    @patch('shared.git.get_remote_url', return_value='https://github.com/test-owner/test-repo.git')
    @patch('shared.git.get_current_branch', return_value='feature-branch')
    @patch('shutil.which', return_value='/usr/bin/git')
    def test_pr_create_autogenerated_title_body(self, mock_which, mock_get_current_branch, mock_get_remote_url, mock_subprocess_run, mock_github_client, mock_load_config):
        # Arrange
        args = MagicMock()
        args.action = 'create'
        args.project_dir = self.project_dir
        args.title = None
        args.body = None
        args.base = 'main'
        args.draft = False
        args.profile = None

        mock_subprocess_run.return_value = MagicMock(
            stdout='feat: Implement new feature\n\nThis is the commit body.',
            check=True
        )
        mock_client_instance = mock_github_client.return_value
        mock_client_instance.get_repo_info_from_remote.return_value = ('github.com', 'test-owner', 'test-repo')
        mock_client_instance.create_pr.return_value = 'https://github.com/test-owner/test-repo/pull/1'

        # Act
        with self.assertRaises(SystemExit) as cm:
            run_pr(args)

        # Assert
        self.assertEqual(cm.exception.code, 0)
        mock_subprocess_run.assert_called_once_with(
            ['/usr/bin/git', '-C', str(self.project_dir), 'log', '-1', '--pretty=%s%n%b'],
            capture_output=True, text=True, check=True
        )
        mock_client_instance.create_pr.assert_called_once_with(
            owner='test-owner',
            repo='test-repo',
            title='feat: Implement new feature',
            body='This is the commit body.',
            head='feature-branch',
            base='main',
            draft=False
        )

if __name__ == '__main__':
    unittest.main()
