import os
import stat
import subprocess
from pathlib import Path

def run_auto_fix_logic(project_dir: Path) -> bool:
    print(f"--- Running Auto-Fix in {project_dir} ---")

    # 1. Initialize git repository if missing
    git_dir = project_dir / ".git"
    if not git_dir.exists():
        print("  [+] Git repository not found. Initializing...")
        try:
            subprocess.run(["git", "init"], cwd=project_dir, check=True, capture_output=True)
            print("  [+] Successfully initialized git repository.")
        except Exception as e:
            print(f"  [-] Failed to initialize git repository: {e}")

    # 2. Create missing directories
    dirs_to_create = ["agents/logs", "agents/archives", ".agent_trash"]
    for d in dirs_to_create:
        dir_path = project_dir / d
        if not dir_path.exists():
            print(f"  [+] Creating missing directory: {d}")
            dir_path.mkdir(parents=True, exist_ok=True)

    # 3. Fix permissions for executable scripts
    files_to_chmod = ["main.py", "run_tests.sh", "safe_run.sh", "bin/start_agent"]
    for f in files_to_chmod:
        file_path = project_dir / f
        if file_path.exists():
            st = os.stat(file_path)
            # Add execute permissions for user, group, and others
            if not bool(st.st_mode & stat.S_IXUSR):
                print(f"  [+] Fixing executable permissions on: {f}")
                os.chmod(file_path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # 4. Create dummy config if missing
    config_path = project_dir / "agent_config.yaml"
    if not config_path.exists():
        print("  [+] Creating default agent_config.yaml")
        config_path.write_text("model: gemini-1.5-pro\n")

    # 5. Create .gitignore if missing
    gitignore_path = project_dir / ".gitignore"
    if not gitignore_path.exists():
        print("  [+] Creating default .gitignore")
        gitignore_content = """# Auto-generated by Auto-Fix
__pycache__/
*.pyc
.env
.agent_trash/
agents/logs/
agents/archives/
"""
        gitignore_path.write_text(gitignore_content)

    print("✅ Auto-Fix complete.")
    return True
