import os
import sys
import shutil
import json
import http.server
import socketserver
import webbrowser
from pathlib import Path
from datetime import datetime
from typing import Optional, List, Dict, Any

from shared.cli_utils import (
    get_workflow_stage,
    WORKFLOW_STAGES,
    _parse_metrics,
    _find_metrics_file,
    _format_duration
)
from shared.adr import ADRManager
from shared.network import run_network_logic

class DocsGenerator:
    def __init__(self, project_dir: Path, output_dir: Path):
        self.project_dir = project_dir.resolve()
        self.output_dir = output_dir.resolve()
        self.css = """
        :root { --primary: #2563eb; --bg: #f8fafc; --text: #1e293b; --card-bg: #ffffff; --border: #e2e8f0; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
               background: var(--bg); color: var(--text); margin: 0; padding: 0; line-height: 1.6; }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        header { background: var(--card-bg); border-bottom: 1px solid var(--border); padding: 1rem 0; margin-bottom: 2rem; }
        header .container { display: flex; justify-content: space-between; align-items: center; }
        h1, h2, h3 { margin-top: 0; color: #0f172a; }
        nav a { margin-left: 1.5rem; text-decoration: none; color: #64748b; font-weight: 500; }
        nav a:hover, nav a.active { color: var(--primary); }
        .card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 0.5rem; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }
        table { width: 100%; border-collapse: collapse; }
        th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid var(--border); }
        th { font-weight: 600; color: #64748b; }
        .status-badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 9999px; font-size: 0.875rem; font-weight: 500; }
        .status-passed { background: #dcfce7; color: #166534; }
        .status-failed { background: #fee2e2; color: #991b1b; }
        .status-unknown { background: #f1f5f9; color: #64748b; }
        footer { text-align: center; color: #94a3b8; padding: 2rem 0; font-size: 0.875rem; }
        """

    def _generate_page(self, title: str, content: str, active_tab: str) -> str:
        nav_links = [
            ("Home", "index.html"),
            ("Features", "features.html"),
            ("Architecture", "architecture.html"),
            ("Metrics", "metrics.html"),
            ("Team", "team.html"),
        ]
        nav_html = "".join([f'<a href="{link}" class="{ "active" if name == active_tab else "" }">{name}</a>' for name, link in nav_links])

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Project Docs</title>
    <style>{self.css}</style>
</head>
<body>
    <header>
        <div class="container">
            <h1>{self.project_dir.name} Docs</h1>
            <nav>{nav_html}</nav>
        </div>
    </header>
    <div class="container">
        {content}
    </div>
    <footer>
        Generated by Combined Autonomous Coding Agent on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
    </footer>
</body>
</html>
"""

    def build(self):
        """Generates the static site."""
        if not self.output_dir.exists():
            self.output_dir.mkdir(parents=True, exist_ok=True)

        print(f"Building documentation site in: {self.output_dir}")

        self._build_index()
        self._build_features()
        self._build_architecture()
        self._build_metrics()
        self._build_team()

        print("✅ Build complete.")

    def _build_index(self):
        stage_key = get_workflow_stage(self.project_dir)
        stage_name = WORKFLOW_STAGES[stage_key]['name']

        # Get latest metrics
        metrics = {}
        history_file = self.project_dir / ".agent_history"
        if history_file.exists():
            with open(history_file, "r") as f:
                run_ids = [line.strip() for line in f if line.strip()]
            if run_ids:
                metrics_file = _find_metrics_file(run_ids[-1], self.project_dir)
                if metrics_file:
                    metrics = _parse_metrics(metrics_file)

        content = f"""
        <div class="card">
            <h2>Project Status</h2>
            <p><strong>Workflow Stage:</strong> {stage_name}</p>
            <p><strong>Last Updated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
        </div>

        <div class="grid">
            <div class="card">
                <h3>Quick Stats</h3>
                <table>
                    <tr><td>Total Iterations</td><td>{metrics.get('Total Iterations', 'N/A')}</td></tr>
                    <tr><td>Total Errors</td><td>{metrics.get('Total Errors', 'N/A')}</td></tr>
                    <tr><td>Execution Time</td><td>{_format_duration(metrics.get('Total Execution Time (s)', 0))}</td></tr>
                </table>
            </div>
            <div class="card">
                <h3>Context</h3>
                <p>See <a href="architecture.html">Architecture</a> for dependency graphs.</p>
                <p>See <a href="features.html">Features</a> for implementation status.</p>
            </div>
        </div>
        """

        html = self._generate_page("Home", content, "Home")
        (self.output_dir / "index.html").write_text(html, encoding="utf-8")

    def _build_features(self):
        feature_file = self.project_dir / "feature_list.json"
        features_html = ""

        if feature_file.exists():
            try:
                with open(feature_file, 'r') as f:
                    data = json.load(f)

                features = data.get("features", [])
                if not features:
                     features_html = "<p>No features found in feature_list.json</p>"
                else:
                    features_html = "<table><thead><tr><th>ID</th><th>Title</th><th>Description</th><th>Status</th></tr></thead><tbody>"
                    for ft in features:
                        status = "Passed" if ft.get("passes") else "Pending"
                        status_class = "status-passed" if ft.get("passes") else "status-unknown"
                        features_html += f"""
                        <tr>
                            <td>{ft.get('id', '')}</td>
                            <td>{ft.get('title', '')}</td>
                            <td>{ft.get('description', '')}</td>
                            <td><span class="status-badge {status_class}">{status}</span></td>
                        </tr>
                        """
                    features_html += "</tbody></table>"
            except Exception as e:
                features_html = f"<p>Error parsing feature_list.json: {e}</p>"
        else:
            features_html = "<p>feature_list.json not found.</p>"

        content = f"""
        <div class="card">
            <h2>Feature List</h2>
            {features_html}
        </div>
        """

        html = self._generate_page("Features", content, "Features")
        (self.output_dir / "features.html").write_text(html, encoding="utf-8")

    def _build_architecture(self):
        # ADRs
        adr_manager = ADRManager(self.project_dir)
        adrs = adr_manager.list_adrs()

        adrs_html = "<table><thead><tr><th>File</th><th>Title</th><th>Status</th></tr></thead><tbody>"
        if not adrs:
            adrs_html += "<tr><td colspan='3'>No ADRs found.</td></tr>"
        else:
            for adr in adrs:
                adrs_html += f"<tr><td>{adr['filename']}</td><td>{adr['title']}</td><td>{adr['status']}</td></tr>"
        adrs_html += "</tbody></table>"

        # Network Graph
        # We generate the network graph HTML in the output dir
        graph_file = self.output_dir / "network_graph.html"
        # Always regenerate to be fresh
        run_network_logic(self.project_dir, graph_file, include_authors=True, limit=50)

        content = f"""
        <div class="card">
            <h2>Architecture Decision Records</h2>
            {adrs_html}
        </div>

        <div class="card" style="height: 600px; padding: 0; overflow: hidden;">
            <h2 style="padding: 1.5rem; margin: 0; border-bottom: 1px solid var(--border);">Dependency Graph</h2>
            <iframe src="network_graph.html" style="width: 100%; height: 530px; border: none;"></iframe>
        </div>
        """

        html = self._generate_page("Architecture", content, "Architecture")
        (self.output_dir / "architecture.html").write_text(html, encoding="utf-8")

    def _build_metrics(self):
        # Gather history
        history_file = self.project_dir / ".agent_history"
        rows = ""
        if history_file.exists():
            with open(history_file, "r") as f:
                run_ids = [line.strip() for line in reversed(f.readlines()) if line.strip()]

            for run_id in run_ids[:20]: # Last 20 runs
                metrics_file = _find_metrics_file(run_id, self.project_dir)
                metrics = _parse_metrics(metrics_file) if metrics_file else {}

                rows += f"""
                <tr>
                    <td>{run_id}</td>
                    <td>{metrics.get('Agent Type', 'N/A')}</td>
                    <td>{metrics.get('Model', 'N/A')}</td>
                    <td>{_format_duration(metrics.get('Total Execution Time (s)', 0))}</td>
                    <td>{metrics.get('Total Iterations', '0')}</td>
                    <td>{metrics.get('Total Errors', '0')}</td>
                </tr>
                """

        if not rows:
            rows = "<tr><td colspan='6'>No history found.</td></tr>"

        content = f"""
        <div class="card">
            <h2>Run History</h2>
            <table>
                <thead>
                    <tr>
                        <th>Run ID</th>
                        <th>Agent</th>
                        <th>Model</th>
                        <th>Time</th>
                        <th>Iterations</th>
                        <th>Errors</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        """

        html = self._generate_page("Metrics", content, "Metrics")
        (self.output_dir / "metrics.html").write_text(html, encoding="utf-8")

    def _build_team(self):
        # Simple git contributors extraction
        import subprocess

        contributors_html = ""
        git_path = shutil.which("git")
        if git_path and (self.project_dir / ".git").is_dir():
            try:
                cmd = [git_path, "-C", str(self.project_dir), "shortlog", "-sn", "HEAD"]
                result = subprocess.run(cmd, capture_output=True, text=True)
                if result.stdout.strip():
                    contributors_html = "<ul>"
                    for line in result.stdout.strip().split('\n'):
                        # format:  10  Name
                        parts = line.strip().split('\t')
                        if len(parts) == 2:
                            count, name = parts
                            contributors_html += f"<li><strong>{name}</strong>: {count} commits</li>"
                        else:
                            contributors_html += f"<li>{line}</li>"
                    contributors_html += "</ul>"
                else:
                    contributors_html = "<p>No contributors found.</p>"
            except Exception as e:
                contributors_html = f"<p>Error getting contributors: {e}</p>"
        else:
            contributors_html = "<p>Not a git repository.</p>"

        content = f"""
        <div class="card">
            <h2>Contributors</h2>
            {contributors_html}
        </div>
        """

        html = self._generate_page("Team", content, "Team")
        (self.output_dir / "team.html").write_text(html, encoding="utf-8")

    def clean(self):
        """Removes the generated site."""
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
            print(f"✅ Cleaned documentation site: {self.output_dir}")
        else:
            print("Docs directory not found.")

    def serve(self, port: int = 8000):
        """Serves the site locally."""
        if not self.output_dir.exists():
            print("Docs not found. Building first...")
            self.build()

        os.chdir(self.output_dir)
        handler = http.server.SimpleHTTPRequestHandler
        # Bind to localhost for security
        with socketserver.TCPServer(("127.0.0.1", port), handler) as httpd:
            print(f"Serving docs at http://127.0.0.1:{port}")
            print("Press Ctrl+C to stop.")
            webbrowser.open(f"http://127.0.0.1:{port}")
            try:
                httpd.serve_forever()
            except KeyboardInterrupt:
                print("\nStopping server.")

def run_docs(args):
    """Entry point for docs command."""
    project_dir = args.project_dir.resolve()

    # Determine output dir
    if args.output:
        output_dir = Path(args.output).resolve()
    else:
        output_dir = project_dir / "docs" / "site"

    generator = DocsGenerator(project_dir, output_dir)

    if args.action == "build":
        generator.build()
    elif args.action == "clean":
        generator.clean()
    elif args.action == "serve":
        port = args.port if args.port else 8000
        generator.serve(port)
    else:
        print(f"Unknown action: {args.action}")
        sys.exit(1)
