"""
Git Hooks Manager
=================

Manages the installation, removal, and execution of git hooks for the project.
"""

import os
import sys
import stat
from pathlib import Path
import subprocess
from typing import Optional, List, Dict, Union

from shared.config_loader import load_config_from_file

# Generic template that calls the agent back
HOOK_SCRIPT_TEMPLATE = """#!/bin/sh
# Auto-generated by Combined Autonomous Coding Agent
# This hook runs the agent's 'hooks run' command.

echo "--- [Agent] Git Hook: {hook_name} ---"

# The agent script that installed this hook
PYTHON_EXE="{python_exe}"
AGENT_SCRIPT="{agent_script}"

if [ ! -f "$AGENT_SCRIPT" ]; then
    echo "❌ Error: Agent script not found at $AGENT_SCRIPT"
    echo "   Please reinstall the hooks or check the path."
    exit 1
fi

# Run the agent hook logic
"$PYTHON_EXE" "$AGENT_SCRIPT" hooks run {hook_name} --project-dir .
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ {hook_name} failed. Action aborted."
    exit 1
fi

exit 0
"""

def install_hooks(project_dir: Path, python_exe: str = sys.executable, agent_script: str = None) -> bool:
    """
    Installs git hooks defined in agent_config.yaml in the .git/hooks directory.

    Args:
        project_dir: The root directory of the project.
        python_exe: The python executable to use in the hook (default: sys.executable).
        agent_script: The path to the agent script (default: calculated from sys.argv[0]).
    """
    git_dir = project_dir / ".git"
    if not git_dir.exists():
        print("❌ Error: Not a git repository.")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # Load configuration
    config = load_config_from_file(project_dir / "agent_config.yaml")
    git_hooks = config.get("git_hooks", {})

    # Fallback to default pre-commit if no config
    if not git_hooks:
        print("ℹ️  No 'git_hooks' section found in agent_config.yaml. Installing default pre-commit hook.")
        git_hooks = {"pre-commit": ["lint", "test"]}

    # Resolve paths
    if agent_script is None:
        agent_script = str(Path(sys.argv[0]).resolve())

    success_count = 0
    for hook_name in git_hooks:
        hook_path = hooks_dir / hook_name

        if hook_path.exists():
            # Check if it's our hook
            try:
                content = hook_path.read_text()
                if "Combined Autonomous Coding Agent" not in content:
                    print(f"⚠️  Skipping {hook_name}: A hook already exists and was not generated by this agent.")
                    continue
            except Exception:
                pass

        script_content = HOOK_SCRIPT_TEMPLATE.format(
            python_exe=python_exe,
            agent_script=agent_script,
            hook_name=hook_name
        )

        try:
            hook_path.write_text(script_content)
            # Make executable
            st = os.stat(hook_path)
            os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
            print(f"✅ Installed hook: {hook_name}")
            success_count += 1
        except Exception as e:
            print(f"❌ Error installing hook {hook_name}: {e}")

    if success_count > 0:
        return True
    return False

# Backward compatibility alias
install_pre_commit_hook = install_hooks

def uninstall_hooks(project_dir: Path) -> bool:
    """
    Uninstalls all agent-managed git hooks.
    """
    hooks_dir = project_dir / ".git" / "hooks"
    if not hooks_dir.exists():
        print("Hooks directory not found.")
        return True

    count = 0
    for hook_path in hooks_dir.iterdir():
        if hook_path.is_file():
            try:
                content = hook_path.read_text()
                if "Combined Autonomous Coding Agent" in content:
                    hook_path.unlink()
                    print(f"✅ Uninstalled hook: {hook_path.name}")
                    count += 1
            except Exception as e:
                print(f"Error checking {hook_path.name}: {e}")

    if count == 0:
        print("No agent-managed hooks found to uninstall.")

    return True

# Backward compatibility alias
uninstall_pre_commit_hook = uninstall_hooks

def run_hooks_logic(project_dir: Path, hook_name: str = None) -> bool:
    """
    Runs the logic for a specific hook (or default checks if none specified).
    """
    print(f"--- Running Git Hook Logic in: {project_dir} ---")

    # Load configuration
    config = load_config_from_file(project_dir / "agent_config.yaml")
    git_hooks = config.get("git_hooks", {})

    python_exe = sys.executable
    agent_script = str(Path(sys.argv[0]).resolve())

    # Default logic if no hook_name provided or config missing (Backward Compatibility)
    if not hook_name:
        # If no hook name is provided, we assume manual invocation of "hooks run"
        # which traditionally ran lint and test.
        print("ℹ️  No hook name provided. Running default checks (Lint & Test).")
        commands = [
            {"command": "lint", "args": ["--project-dir", str(project_dir)]},
            {"command": "test", "args": ["--project-dir", str(project_dir)]}
        ]
    else:
        print(f"Hook: {hook_name}")
        commands_config = git_hooks.get(hook_name)

        if commands_config is None:
            # If the hook name matches 'pre-commit' but isn't in config, run defaults
            if hook_name == "pre-commit" and not git_hooks:
                 print("ℹ️  No config for 'pre-commit'. Running default checks.")
                 commands = [
                    {"command": "lint", "args": ["--project-dir", str(project_dir)]},
                    {"command": "test", "args": ["--project-dir", str(project_dir)]}
                ]
            else:
                print(f"❌ Error: No configuration found for hook '{hook_name}' in agent_config.yaml.")
                return False
        else:
            commands = []
            for cmd_item in commands_config:
                if isinstance(cmd_item, str):
                    # It's a raw shell command string
                    commands.append(cmd_item)
                elif isinstance(cmd_item, dict):
                    # Structured command
                    base = cmd_item.get("command")
                    args = cmd_item.get("args", [])
                    # If args is a string, split it? No, assume list for safety or simple string.
                    if isinstance(args, str):
                        args = args.split()

                    # If the command is an agent subcommand (like 'lint', 'test'), prepend python and agent script
                    # This is a heuristic. Config could specify full commands too.
                    # To simplify, we can treat "lint" and "test" as internal shortcuts.
                    if base in ["lint", "test", "security", "verify", "arch"]:
                         # Ensure --project-dir is passed if not present
                         # But be careful about duplications if user added it in args
                         cmd_dict = {
                             "command": base,
                             "args": args
                         }
                         # We'll inject project_dir during execution setup below if needed
                         commands.append(cmd_dict)
                    else:
                         # External command
                         full_cmd = [base] + args
                         commands.append(full_cmd)

    # Execute commands
    for i, cmd in enumerate(commands):
        print(f"\n[{i+1}/{len(commands)}] Running: {cmd}")

        try:
            if isinstance(cmd, str):
                # Shell=True for string commands
                res = subprocess.run(cmd, shell=True, cwd=project_dir)  # nosec
            elif isinstance(cmd, dict):
                # Internal Agent Command Shortcut
                # We invoke a new subprocess for the agent
                sub_cmd = cmd["command"]
                sub_args = cmd["args"]

                # Automatically add --project-dir if not present and it's likely needed
                if "--project-dir" not in sub_args and "-p" not in sub_args:
                    sub_args.extend(["--project-dir", str(project_dir)])

                args = [python_exe, agent_script, sub_cmd] + sub_args
                res = subprocess.run(args, cwd=project_dir)
            elif isinstance(cmd, list):
                # External command list
                res = subprocess.run(cmd, cwd=project_dir)
            else:
                print(f"❌ Unknown command format: {cmd}")
                return False

            if res.returncode != 0:
                print(f"❌ Command failed with exit code {res.returncode}.")
                return False

        except Exception as e:
            print(f"❌ Error executing command: {e}")
            return False

    print(f"\n✅ Hook '{hook_name or 'default'}' passed.")
    return True
