"""
Git Hooks Manager
=================

Manages the installation, removal, and execution of git hooks for the project.
"""

import os
import sys
import stat
from pathlib import Path
import subprocess
import shlex

HOOK_SCRIPT_TEMPLATE = """#!/bin/sh
# Auto-generated by Combined Autonomous Coding Agent
# This hook runs the agent's configurable checks.

echo "--- [Agent] {hook_name} Hook ---"

# The agent script that installed this hook
PYTHON_EXE="{python_exe}"
AGENT_SCRIPT="{agent_script}"

if [ ! -f "$AGENT_SCRIPT" ]; then
    echo "❌ Error: Agent script not found at $AGENT_SCRIPT"
    echo "   Please reinstall the hook or check the path."
    exit 1
fi

# Run the agent hook command
"$PYTHON_EXE" "$AGENT_SCRIPT" hooks run "{hook_name}" --project-dir .
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ {hook_name} checks failed. Operation aborted."
    exit 1
fi

echo "✅ {hook_name} checks passed!"
exit 0
"""

def install_hooks(project_dir: Path, hooks_config: dict[str, list[str]], python_exe: str = sys.executable, agent_script: str = None) -> bool:
    """
    Installs git hooks defined in the configuration.

    Args:
        project_dir: The root directory of the project.
        hooks_config: A dictionary mapping hook names to lists of commands.
        python_exe: The python executable to use.
        agent_script: The path to the agent script.
    """
    git_dir = project_dir / ".git"
    if not git_dir.exists():
        print("❌ Error: Not a git repository.")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    if agent_script is None:
        agent_script = str(Path(sys.argv[0]).resolve())

    success = True
    # If hooks_config is None or empty, we install defaults if backward compat or warn?
    # Let's assume defaults are handled by caller or config loader.
    if not hooks_config:
        print("ℹ️  No hooks defined in configuration. Nothing to install.")
        return True

    for hook_name in hooks_config:
        hook_path = hooks_dir / hook_name

        if hook_path.exists():
            try:
                content = hook_path.read_text()
                if "Combined Autonomous Coding Agent" not in content:
                    print(f"⚠️  Skipping {hook_name}: A hook already exists and was not generated by this agent.")
                    continue
            except Exception:
                pass

        script_content = HOOK_SCRIPT_TEMPLATE.format(
            python_exe=python_exe,
            agent_script=agent_script,
            hook_name=hook_name
        )

        try:
            hook_path.write_text(script_content)
            st = os.stat(hook_path)
            os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
            print(f"✅ Installed hook: {hook_name}")
        except Exception as e:
            print(f"❌ Error installing {hook_name}: {e}")
            success = False

    return success

def uninstall_hooks(project_dir: Path) -> bool:
    """
    Uninstalls all hooks created by the agent.
    """
    hooks_dir = project_dir / ".git" / "hooks"
    if not hooks_dir.exists():
        return True

    try:
        found = False
        for hook_path in hooks_dir.iterdir():
            if hook_path.is_file():
                try:
                    content = hook_path.read_text()
                    if "Combined Autonomous Coding Agent" in content:
                        hook_path.unlink()
                        print(f"✅ Uninstalled hook: {hook_path.name}")
                        found = True
                except Exception:
                    pass
        if not found:
            print("No agent hooks found to uninstall.")
        return True
    except Exception as e:
        print(f"❌ Error uninstalling hooks: {e}")
        return False

def run_hook_logic(project_dir: Path, hook_name: str, hooks_config: dict[str, list[str]]) -> bool:
    """
    Runs the commands defined for a specific hook.
    """
    print(f"--- Running {hook_name} checks in: {project_dir} ---")

    if not hooks_config or hook_name not in hooks_config:
        print(f"ℹ️  No configuration found for hook: {hook_name}")
        return True

    commands = hooks_config[hook_name]
    if not commands:
        print("  (No commands configured)")
        return True

    python_exe = sys.executable
    agent_script = str(Path(sys.argv[0]).resolve())

    all_passed = True
    for cmd_str in commands:
        print(f"\n> Running: {cmd_str}")

        parts = shlex.split(cmd_str)
        if not parts:
            continue

        exe = parts[0]
        args = parts[1:]

        # Heuristic: If 'exe' is a known agent command, run it via the agent script.
        KNOWN_COMMANDS = ["lint", "test", "security", "verify", "format", "analyze", "secrets", "check-links", "debt", "health"]

        if exe in KNOWN_COMMANDS:
            cmd = [python_exe, agent_script, exe, "--project-dir", str(project_dir)] + args
        else:
            # Regular shell command
            cmd = parts

        try:
            res = subprocess.run(cmd, cwd=project_dir)
            if res.returncode != 0:
                print(f"❌ Command failed: {cmd_str}")
                all_passed = False
                break # Stop on first failure
        except Exception as e:
            print(f"❌ Error executing command '{cmd_str}': {e}")
            all_passed = False
            break

    if all_passed:
        print(f"\n✅ {hook_name} passed.")
        return True
    else:
        return False

# Backward compatibility wrappers
def install_pre_commit_hook(project_dir: Path, python_exe: str = sys.executable, agent_script: str = None) -> bool:
    # Default config for backward compat
    config = {"pre-commit": ["lint", "test"]}
    return install_hooks(project_dir, config, python_exe, agent_script)

def uninstall_pre_commit_hook(project_dir: Path) -> bool:
    return uninstall_hooks(project_dir)

def run_hooks_logic(project_dir: Path) -> bool:
    config = {"pre-commit": ["lint", "test"]}
    return run_hook_logic(project_dir, "pre-commit", config)
