"""
Git Hooks Manager
=================

Manages the installation, removal, and execution of git hooks for the project.
"""

import os
import sys
import stat
from pathlib import Path
import subprocess

HOOK_SCRIPT_TEMPLATE = """#!/bin/sh
# Auto-generated by Combined Autonomous Coding Agent
# This hook runs the agent's lint and test commands before commit.

echo "--- [Agent] Pre-commit Hook ---"

# The agent script that installed this hook
PYTHON_EXE="{python_exe}"
AGENT_SCRIPT="{agent_script}"

if [ ! -f "$AGENT_SCRIPT" ]; then
    echo "❌ Error: Agent script not found at $AGENT_SCRIPT"
    echo "   Please reinstall the hook or check the path."
    exit 1
fi

# Run lint
echo "Running lint..."
"$PYTHON_EXE" "$AGENT_SCRIPT" lint --project-dir .
LINT_EXIT_CODE=$?

if [ $LINT_EXIT_CODE -ne 0 ]; then
    echo "❌ Linting failed. Commit aborted."
    exit 1
fi

# Run tests
echo "Running tests..."
"$PYTHON_EXE" "$AGENT_SCRIPT" test --project-dir .
TEST_EXIT_CODE=$?

if [ $TEST_EXIT_CODE -ne 0 ]; then
    echo "❌ Tests failed. Commit aborted."
    exit 1
fi

echo "✅ All checks passed!"
exit 0
"""


def install_pre_commit_hook(project_dir: Path, python_exe: str = sys.executable, agent_script: str = None) -> bool:
    """
    Installs a pre-commit hook in the .git/hooks directory.

    Args:
        project_dir: The root directory of the project.
        python_exe: The python executable to use in the hook (default: sys.executable).
        agent_script: The path to the agent script (default: calculated from sys.argv[0]).
    """
    git_dir = project_dir / ".git"
    if not git_dir.exists():
        print("❌ Error: Not a git repository.")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"

    if hook_path.exists():
        # Check if it's our hook
        try:
            content = hook_path.read_text()
            if "Combined Autonomous Coding Agent" not in content:
                print(f"❌ Error: A pre-commit hook already exists at {hook_path}.")
                print("   To overwrite it, please delete it manually first.")
                return False
        except Exception:
            pass

    # Resolve paths
    if agent_script is None:
        agent_script = str(Path(sys.argv[0]).resolve())

    script_content = HOOK_SCRIPT_TEMPLATE.format(
        python_exe=python_exe,
        agent_script=agent_script
    )

    try:
        hook_path.write_text(script_content)
        # Make executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        print(f"✅ Pre-commit hook installed at {hook_path}")
        return True
    except Exception as e:
        print(f"❌ Error installing hook: {e}")
        return False


def uninstall_pre_commit_hook(project_dir: Path) -> bool:
    """
    Uninstalls the pre-commit hook if it was created by the agent.
    """
    hook_path = project_dir / ".git" / "hooks" / "pre-commit"
    if not hook_path.exists():
        print("Pre-commit hook not found.")
        return True

    try:
        content = hook_path.read_text()
        if "Combined Autonomous Coding Agent" in content:
            hook_path.unlink()
            print("✅ Pre-commit hook uninstalled.")
            return True
        else:
            print("❌ Error: The existing pre-commit hook was not generated by this agent.")
            print("   Aborting uninstall to prevent data loss.")
            return False
    except Exception as e:
        print(f"❌ Error uninstalling hook: {e}")
        return False


def run_hooks_logic(project_dir: Path) -> bool:
    """
    Manually runs the logic that the pre-commit hook would run.
    """
    print(f"--- Running Pre-commit Hooks Manual Check in: {project_dir} ---")

    python_exe = sys.executable
    agent_script = str(Path(sys.argv[0]).resolve())

    # 1. Lint
    print("\n[1/2] Running Lint...")
    # We execute a subprocess to ensure clean environment and separation
    res_lint = subprocess.run([python_exe, agent_script, "lint", "-p", str(project_dir)])  # nosec
    if res_lint.returncode != 0:
        print("❌ Lint check failed.")
        return False

    # 2. Test
    print("\n[2/2] Running Tests...")
    res_test = subprocess.run([python_exe, agent_script, "test", "-p", str(project_dir)])  # nosec
    if res_test.returncode != 0:
        print("❌ Test check failed.")
        return False

    print("\n✅ All hooks passed.")
    return True
