import json
import sys
import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from typing import Any, Dict, List, Union


class Json2XmlManager:
    """Manages conversion from JSON format to XML."""

    def __init__(self, project_dir: Path = None):
        self.project_dir = project_dir

    def _dict_to_xml(self, d: Union[Dict, List, Any], root_node: ET.Element):
        if isinstance(d, dict):
            for k, v in d.items():
                if k == "@attributes" and isinstance(v, dict):
                    for attr_k, attr_v in v.items():
                        root_node.set(attr_k, str(attr_v))
                elif k == "#text":
                    root_node.text = str(v)
                elif isinstance(v, list):
                    for item in v:
                        child = ET.SubElement(root_node, k)
                        self._dict_to_xml(item, child)
                elif isinstance(v, dict):
                    child = ET.SubElement(root_node, k)
                    self._dict_to_xml(v, child)
                else:
                    child = ET.SubElement(root_node, k)
                    child.text = str(v)
        elif isinstance(d, list):
            for item in d:
                child = ET.SubElement(root_node, "item")
                self._dict_to_xml(item, child)
        else:
            root_node.text = str(d)

    def convert(self, json_data: Union[str, Dict[str, Any]]) -> str:
        """Converts JSON data to formatted XML string."""
        if isinstance(json_data, str):
            try:
                data = json.loads(json_data)
            except json.JSONDecodeError as e:
                raise ValueError(f"Invalid JSON string: {e}")
        else:
            data = json_data

        if not data:
            return ""

        # Determine root element
        if isinstance(data, dict) and len(data) == 1:
            root_key = list(data.keys())[0]
            root_val = data[root_key]
            root = ET.Element(root_key)
            self._dict_to_xml(root_val, root)
        else:
            root = ET.Element("root")
            self._dict_to_xml(data, root)

        xmlstr = ET.tostring(root, encoding='utf-8')
        # Pretty print
        parsed = minidom.parseString(xmlstr)  # nosec B318
        pretty_xml_as_string = parsed.toprettyxml(indent="  ")
        # Remove the XML declaration generated by toprettyxml if present
        # minidom adds <?xml version="1.0" ?>
        lines = pretty_xml_as_string.split("\n")
        if lines and "<?xml" in lines[0]:
            lines = lines[1:]

        return "\n".join(lines).strip()


def run_json2xml_lab_logic(args) -> bool:
    """CLI handler for json2xml lab."""
    if getattr(args, "tui", False):
        from shared.tui import AgentTUI
        print("Launching JSON to XML Lab TUI...")
        app = AgentTUI(project_dir=getattr(args, 'project_dir', None), start_tab="tab-json2xml")
        import asyncio
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None
        if loop and loop.is_running():
            asyncio.ensure_future(app.run_async())
        else:
            app.run()
        sys.exit(0)

    manager = Json2XmlManager()

    input_data = None
    if getattr(args, "file", None):
        try:
            with open(args.file, 'r', encoding='utf-8') as f:
                input_data = f.read()
        except Exception as e:
            print(f"Error reading file '{args.file}': {e}", file=sys.stderr)
            return False
    elif getattr(args, "text", None):
        input_data = args.text
    else:
        # read from stdin
        if not sys.stdin.isatty():
            input_data = sys.stdin.read()
        else:
            print("Error: Either --file, --text, or piped stdin must be provided.", file=sys.stderr)
            return False

    try:
        xml_output = manager.convert(input_data)
    except ValueError as e:
        print(f"Error converting JSON to XML: {e}", file=sys.stderr)
        return False

    output_path = getattr(args, "output", None)
    if output_path:
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(xml_output)
            print(f"✅ Successfully converted to {output_path}")
            return True
        except Exception as e:
            print(f"Error writing to '{output_path}': {e}", file=sys.stderr)
            return False
    else:
        print(xml_output)
        return True
