from pathlib import Path
from textual.app import ComposeResult
from textual.widgets import Label, Button, Input, Select, TextArea, Markdown, RichLog
from textual.containers import Container, Vertical, Horizontal, VerticalScroll
from textual import on
from rich.syntax import Syntax
import io
import contextlib
import asyncio

from shared.presentation import PresentationGenerator

class PresentationTab(Container):
    """Tab for generating and viewing project presentations."""

    def __init__(self, project_dir: Path, **kwargs) -> None:
        super().__init__(**kwargs)
        self.project_dir = project_dir
        self.presentation_file = self.project_dir / "presentation.md"

    def compose(self) -> ComposeResult:
        with Vertical():
            yield Label("[bold]Presentation Generator[/bold]", classes="welcome-text")

            # Configuration
            with Vertical(classes="stat-box"):
                with Horizontal():
                    yield Label("Theme:")
                    yield Select.from_values(["default", "gaia", "uncover"], id="pres-theme", value="default")
                    yield Label("Agent:")
                    yield Select.from_values(["gemini", "cursor", "local", "openrouter"], id="pres-agent", value="gemini")

                with Horizontal():
                    yield Label("Model:")
                    yield Input(placeholder="Model (optional)", id="pres-model")
                    yield Button("Generate (AI)", id="btn-pres-generate", variant="primary")

            with Horizontal(classes="stat-box"):
                yield Button("Save", id="btn-pres-save", variant="success")
                yield Button("Reload", id="btn-pres-reload", variant="warning")
                yield Label("", id="pres-status")

            # Editor and Preview
            with Horizontal():
                # Left: Editor
                with Vertical(id="pres-editor-container"):
                    yield Label("[bold]Markdown Editor[/bold]")
                    yield TextArea(id="pres-editor", language="markdown")

                # Right: Preview
                with VerticalScroll(id="pres-preview-container"):
                    yield Label("[bold]Preview[/bold]")
                    yield Markdown(id="pres-preview")

    def on_mount(self) -> None:
        self.load_presentation()

    async def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "btn-pres-generate":
            await self.generate_presentation()
        elif event.button.id == "btn-pres-save":
            self.save_presentation()
        elif event.button.id == "btn-pres-reload":
            self.load_presentation()

    def load_presentation(self) -> None:
        editor = self.query_one("#pres-editor", TextArea)
        preview = self.query_one("#pres-preview", Markdown)

        if self.presentation_file.exists():
            try:
                content = self.presentation_file.read_text(encoding="utf-8", errors="replace")
                editor.text = content
                preview.update(content)
                self.notify(f"Loaded {self.presentation_file.name}")
            except Exception as e:
                self.notify(f"Error loading file: {e}", severity="error")
        else:
            editor.text = "# Project Presentation\n\nGenerated by Agent."
            preview.update(editor.text)

    def save_presentation(self) -> None:
        editor = self.query_one("#pres-editor", TextArea)
        content = editor.text

        try:
            self.presentation_file.write_text(content, encoding="utf-8")
            self.notify(f"Saved to {self.presentation_file.name}")

            # Update preview
            self.query_one("#pres-preview", Markdown).update(content)
        except Exception as e:
            self.notify(f"Error saving file: {e}", severity="error")

    async def generate_presentation(self) -> None:
        theme = self.query_one("#pres-theme", Select).value or "default"
        agent_type = self.query_one("#pres-agent", Select).value or "gemini"
        model = self.query_one("#pres-model", Input).value or None

        self.notify(f"Generating presentation with {agent_type}...", severity="information", timeout=5)
        self.query_one("#pres-status", Label).update("Generating...")

        # Disable button
        self.query_one("#btn-pres-generate").disabled = True

        generator = PresentationGenerator(self.project_dir, agent_type=agent_type, model=model)

        # Run generation
        # We capture stdout because PresentationGenerator prints to console
        f = io.StringIO()
        success = False
        try:
            with contextlib.redirect_stdout(f):
                # Run in thread to avoid blocking TUI
                success = await generator.generate(self.presentation_file, theme=theme)
        except Exception as e:
            self.notify(f"Generation error: {e}", severity="error")
        finally:
            self.query_one("#btn-pres-generate").disabled = False
            self.query_one("#pres-status", Label).update("")

        if success:
            self.notify("Presentation generated successfully!")
            self.load_presentation()
        else:
            self.notify("Generation failed.", severity="error")

    @on(TextArea.Changed, "#pres-editor")
    def on_editor_changed(self, event: TextArea.Changed) -> None:
        # Live preview update (debounced ideally, but immediate for now)
        self.query_one("#pres-preview", Markdown).update(event.text_area.text)
