from pathlib import Path
import subprocess
import asyncio
from shared.github_client import GitHubClient
from shared.jira_client import JiraClient
from shared.git import push_branch

WORKFLOW_STAGES = {
    "IN_PROGRESS": {"name": "In Progress", "file": None},
    "COMPLETED": {"name": "Completed", "file": "COMPLETED"},
    "QA_PASSED": {"name": "QA Passed", "file": "QA_PASSED"},
    "SIGNED_OFF": {"name": "Signed Off", "file": "PROJECT_SIGNED_OFF"},
}

# Ordered list of stages for advancing/reverting
WORKFLOW_ORDER = ["IN_PROGRESS", "COMPLETED", "QA_PASSED", "SIGNED_OFF"]


def _get_workflow_stage(project_dir: Path):
    """Determines the current workflow stage by checking for marker files."""
    if (project_dir / WORKFLOW_STAGES["SIGNED_OFF"]["file"]).exists():
        return "SIGNED_OFF"
    if (project_dir / WORKFLOW_STAGES["QA_PASSED"]["file"]).exists():
        return "QA_PASSED"
    if (project_dir / WORKFLOW_STAGES["COMPLETED"]["file"]).exists():
        return "COMPLETED"
    return "IN_PROGRESS"

def _get_remote_info(project_dir: Path):
    """Gets the git remote information."""
    try:
        remote_url = subprocess.run(
            ["git", "-C", str(project_dir), "config", "--get", "remote.origin.url"],
            capture_output=True, text=True, check=True
        ).stdout.strip()
        gh_client = GitHubClient()
        return gh_client.get_repo_info_from_remote(remote_url)
    except (subprocess.CalledProcessError, ValueError):
        return None, None, None

def _create_pr(config, branch_name: str):
    """Creates a pull request on GitHub."""
    host, owner, repo = _get_remote_info(config.project_dir)
    if not host or not owner or not repo:
        return None

    gh_client = GitHubClient(host=host)
    metadata = gh_client.get_repo_metadata(owner, repo)
    if not metadata:
        return None

    default_branch = metadata.get("default_branch", "main")
    if branch_name == default_branch:
        return None

    pr_title = f"feat: {config.jira_ticket_key} - Automated PR"
    pr_body = "This pull request was automatically generated by the autonomous coding agent."
    return gh_client.create_pr(owner, repo, branch_name, default_branch, pr_title, pr_body)

async def complete_jira_ticket(config):
    """
    Handles the final Jira ticket completion steps:
    - Pushes the current branch.
    - Creates a Pull Request.
    - Adds a comment to the Jira ticket with the PR link.
    - Transitions the ticket to the 'Done' status.
    """
    if not config.jira or not config.jira_ticket_key:
        return False

    try:
        current_branch = subprocess.run(
            ["git", "-C", str(config.project_dir), "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, check=True
        ).stdout.strip()

        if push_branch(config.project_dir, current_branch):
            pr_url = _create_pr(config, current_branch)
            if pr_url:
                jira_client = JiraClient(config.jira)
                comment = f"Pull request created: {pr_url}"
                if not jira_client.get_issue_comments(config.jira_ticket_key, search_string=comment):
                    jira_client.add_comment(config.jira_ticket_key, comment)

                done_status = config.jira.status_map.get("done", "Done")
                jira_client.transition_issue(config.jira_ticket_key, done_status)
                return True
    except (subprocess.CalledProcessError, Exception):
        return False
    return False
